name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=/angular-template/ --repo=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/antoinedelaplace/angular-template.git --name="Antoine DELAPLACE" --email=antoine.delaplace@gmail.com
